"""The model seam: turn a deterministic analysis into the judgment, drill, and grade.

This is where the load-bearing AI lives. The reasoning lambda does all the counting
and weighting in plain code, then hands this function a structured analysis. The
model's job is the part code cannot fake: decide which domain is genuinely being
avoided (versus mastered, versus not-yet-started), pick today's single focus,
generate one broken-manifest drill for it, and grade yesterday's drill.

=============================== STUB, NOT WIRED ===============================
Right now run_model() returns hardcoded SAMPLE output, clearly tagged
source="STUB". It does NOT call Gemini. Nothing here is real model output.

TODO(phase 3): replace the body of run_model() with a real gemini-2.5-flash call:
  - pull the API key from Secrets Manager (module-level cache, see get_secret)
  - build the prompt from `inp`
  - POST to the Gemini generateContent endpoint, parse the JSON back into
    ModelOutput, and set source="gemini-2.5-flash"
  - validate the generated manifest (apply to a throwaway namespace, confirm it
    breaks in the intended way) before it is ever sent
==============================================================================
"""
from typing import List, Optional, TypedDict


class DomainStat(TypedDict):
    exam: str
    domain: str
    weight: float          # official exam weight, 0..1
    events: int            # activity seen for this domain in the window
    share: float           # this domain's share of my actual activity, 0..1
    expected_share: float  # what its share "should" be, from the weight
    gap: float             # expected_share - share; positive means under-touched


class DecayedSkill(TypedDict):
    skill: str
    last_practised: Optional[str]
    days_since: Optional[int]


class ModelInput(TypedDict):
    date: str
    days_to_exam: dict                 # exam name -> days remaining
    domains: List[DomainStat]          # per-exam per-domain stats, deterministic
    decayed_skills: List[DecayedSkill]
    yesterdays_drill: Optional[dict]   # the drill to grade, or None


class Drill(TypedDict):
    domain: str
    title: str
    manifest: str
    task: str
    est_minutes: int


class Grade(TypedDict):
    drill_date: str
    verdict: str      # e.g. "correct", "partial", "not attempted"
    detail: str


class ModelOutput(TypedDict):
    source: str                 # "STUB" now; "gemini-2.5-flash" once wired
    avoidance_judgment: str
    focus_domain: str
    drill: Drill
    grade: Optional[Grade]


# A clearly fake sample manifest, so nobody mistakes stub output for a real drill.
_SAMPLE_MANIFEST = """\
# [SAMPLE STUB DRILL — not model-generated]
apiVersion: v1
kind: Pod
metadata:
  name: broken-static-pod
  namespace: kube-system
spec:
  containers:
    - name: app
      image: nginx:1.29
      ports:
        - containerPort: 80
      # the readiness probe points at a port nothing listens on
      readinessProbe:
        httpGet:
          path: /
          port: 8080
"""


def run_model(inp: ModelInput) -> ModelOutput:
    """STUB. Returns hardcoded sample output. Does not call any model.

    Replace the body with a real gemini-2.5-flash call in Phase 3 (see the TODO at
    the top of this file). The signature and the ModelOutput shape are the contract
    the reasoning lambda depends on, and will not change when the real call lands.
    """
    focus = inp["domains"][0]["domain"] if inp.get("domains") else "troubleshooting"

    grade: Optional[Grade] = None
    if inp.get("yesterdays_drill"):
        grade = {
            "drill_date": inp["yesterdays_drill"].get("date", "unknown"),
            "verdict": "partial",
            "detail": "[SAMPLE STUB GRADE] fixed the probe port but left the "
                      "container port unchanged. Real grading arrives in Phase 3.",
        }

    return {
        "source": "STUB",
        "avoidance_judgment": (
            "[SAMPLE STUB JUDGMENT] This text is placeholder, not model output. "
            f"The deterministic layer flagged '{focus}' as the most under-touched "
            "domain for its exam weight. In Phase 3 gemini-2.5-flash replaces this "
            "with a real avoidance call over the analysis."
        ),
        "focus_domain": focus,
        "drill": {
            "domain": focus,
            "title": "[SAMPLE STUB DRILL] fix the broken static pod",
            "manifest": _SAMPLE_MANIFEST,
            "task": "This is placeholder drill text. A real, validated drill is "
                    "generated by the model in Phase 3.",
            "est_minutes": 15,
        },
        "grade": grade,
    }
